# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'twitch_sub_v205.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(950, 900)
        Form.setMinimumSize(QtCore.QSize(950, 900))
        self.tier_group = QtWidgets.QGroupBox(Form)
        self.tier_group.setGeometry(QtCore.QRect(430, 10, 461, 111))
        self.tier_group.setObjectName("tier_group")
        self.label_1 = QtWidgets.QLabel(self.tier_group)
        self.label_1.setGeometry(QtCore.QRect(20, 30, 41, 20))
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label_1.setFont(font)
        self.label_1.setObjectName("label_1")
        self.label_2 = QtWidgets.QLabel(self.tier_group)
        self.label_2.setGeometry(QtCore.QRect(130, 30, 41, 20))
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.tier_group)
        self.label_3.setGeometry(QtCore.QRect(240, 30, 41, 20))
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.checkBox_1 = QtWidgets.QCheckBox(self.tier_group)
        self.checkBox_1.setGeometry(QtCore.QRect(80, 35, 21, 16))
        self.checkBox_1.setText("")
        self.checkBox_1.setChecked(True)
        self.checkBox_1.setObjectName("checkBox_1")
        self.checkBox_2 = QtWidgets.QCheckBox(self.tier_group)
        self.checkBox_2.setGeometry(QtCore.QRect(188, 34, 21, 16))
        self.checkBox_2.setText("")
        self.checkBox_2.setChecked(True)
        self.checkBox_2.setObjectName("checkBox_2")
        self.checkBox_3 = QtWidgets.QCheckBox(self.tier_group)
        self.checkBox_3.setGeometry(QtCore.QRect(295, 34, 21, 16))
        self.checkBox_3.setText("")
        self.checkBox_3.setChecked(True)
        self.checkBox_3.setObjectName("checkBox_3")
        self.lineEdit_1 = QtWidgets.QLineEdit(self.tier_group)
        self.lineEdit_1.setGeometry(QtCore.QRect(20, 60, 71, 20))
        self.lineEdit_1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_1.setObjectName("lineEdit_1")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.tier_group)
        self.lineEdit_2.setGeometry(QtCore.QRect(130, 60, 71, 20))
        self.lineEdit_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.tier_group)
        self.lineEdit_3.setGeometry(QtCore.QRect(240, 60, 71, 20))
        self.lineEdit_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.tier_all = QtWidgets.QPushButton(self.tier_group)
        self.tier_all.setGeometry(QtCore.QRect(350, 30, 75, 23))
        self.tier_all.setObjectName("tier_all")
        self.tier_reset = QtWidgets.QPushButton(self.tier_group)
        self.tier_reset.setGeometry(QtCore.QRect(350, 60, 75, 23))
        self.tier_reset.setObjectName("tier_reset")
        self.label_award = QtWidgets.QLabel(Form)
        self.label_award.setGeometry(QtCore.QRect(20, 500, 91, 31))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(16)
        self.label_award.setFont(font)
        self.label_award.setObjectName("label_award")
        self.sub_list = QtWidgets.QTableView(Form)
        self.sub_list.setGeometry(QtCore.QRect(20, 50, 381, 431))
        self.sub_list.setObjectName("sub_list")
        self.label_sub = QtWidgets.QLabel(Form)
        self.label_sub.setGeometry(QtCore.QRect(20, 10, 91, 31))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(16)
        self.label_sub.setFont(font)
        self.label_sub.setObjectName("label_sub")
        self.label_awarder = QtWidgets.QLabel(Form)
        self.label_awarder.setGeometry(QtCore.QRect(780, 500, 111, 31))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(16)
        self.label_awarder.setFont(font)
        self.label_awarder.setObjectName("label_awarder")
        self.new_award = QtWidgets.QLineEdit(Form)
        self.new_award.setGeometry(QtCore.QRect(20, 540, 271, 30))
        self.new_award.setObjectName("new_award")
        self.award_list_c = QtWidgets.QListView(Form)
        self.award_list_c.setGeometry(QtCore.QRect(360, 570, 41, 271))
        self.award_list_c.setObjectName("award_list_c")
        self.new_award_n = QtWidgets.QLineEdit(Form)
        self.new_award_n.setGeometry(QtCore.QRect(290, 540, 52, 30))
        self.new_award_n.setObjectName("new_award_n")
        self.add_award = QtWidgets.QPushButton(Form)
        self.add_award.setGeometry(QtCore.QRect(341, 539, 61, 32))
        self.add_award.setObjectName("add_award")
        self.load_sub = QtWidgets.QPushButton(Form)
        self.load_sub.setGeometry(QtCore.QRect(330, 20, 75, 23))
        self.load_sub.setObjectName("load_sub")
        self.awarder_out = QtWidgets.QPushButton(Form)
        self.awarder_out.setGeometry(QtCore.QRect(430, 500, 91, 31))
        self.awarder_out.setObjectName("awarder_out")
        self.award_list_n = QtWidgets.QListView(Form)
        self.award_list_n.setGeometry(QtCore.QRect(20, 570, 340, 271))
        self.award_list_n.setObjectName("award_list_n")
        self.load_award = QtWidgets.QPushButton(Form)
        self.load_award.setGeometry(QtCore.QRect(110, 510, 61, 23))
        self.load_award.setObjectName("load_award")
        self.save_awarder = QtWidgets.QPushButton(Form)
        self.save_awarder.setGeometry(QtCore.QRect(810, 820, 75, 23))
        self.save_awarder.setObjectName("save_awarder")
        self.tenure = QtWidgets.QRadioButton(Form)
        self.tenure.setGeometry(QtCore.QRect(120, 20, 81, 21))
        self.tenure.setChecked(True)
        self.tenure.setObjectName("tenure")
        self.streak = QtWidgets.QRadioButton(Form)
        self.streak.setGeometry(QtCore.QRect(210, 20, 101, 21))
        self.streak.setChecked(False)
        self.streak.setObjectName("streak")
        self.clear_awarder = QtWidgets.QPushButton(Form)
        self.clear_awarder.setGeometry(QtCore.QRect(430, 820, 75, 23))
        self.clear_awarder.setObjectName("clear_awarder")
        self.awarder_out_all = QtWidgets.QPushButton(Form)
        self.awarder_out_all.setGeometry(QtCore.QRect(530, 500, 91, 31))
        self.awarder_out_all.setObjectName("awarder_out_all")
        self.awarder_list = QtWidgets.QTableWidget(Form)
        self.awarder_list.setGeometry(QtCore.QRect(430, 540, 461, 271))
        self.awarder_list.setObjectName("awarder_list")
        self.awarder_list.setColumnCount(4)
        self.awarder_list.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.awarder_list.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.awarder_list.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.awarder_list.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.awarder_list.setHorizontalHeaderItem(3, item)
        self.subTime_group = QtWidgets.QGroupBox(Form)
        self.subTime_group.setGeometry(QtCore.QRect(430, 130, 461, 351))
        self.subTime_group.setObjectName("subTime_group")
        self.time_group = QtWidgets.QTableWidget(self.subTime_group)
        self.time_group.setGeometry(QtCore.QRect(10, 70, 311, 271))
        self.time_group.setObjectName("time_group")
        self.time_group.setColumnCount(4)
        self.time_group.setRowCount(8)
        item = QtWidgets.QTableWidgetItem()
        self.time_group.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.time_group.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.time_group.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.time_group.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.time_group.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.time_group.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.time_group.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.time_group.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.time_group.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.time_group.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.time_group.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.time_group.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.time_group.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.time_group.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.time_group.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.time_group.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.time_group.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.time_group.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.time_group.setItem(1, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.time_group.setItem(1, 3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.time_group.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.time_group.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.time_group.setItem(2, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.time_group.setItem(2, 3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.time_group.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.time_group.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.time_group.setItem(3, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.time_group.setItem(3, 3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.time_group.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.time_group.setItem(4, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.time_group.setItem(4, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.time_group.setItem(4, 3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.time_group.setItem(5, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.time_group.setItem(5, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.time_group.setItem(5, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.time_group.setItem(5, 3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.time_group.setItem(6, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.time_group.setItem(6, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.time_group.setItem(6, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.time_group.setItem(6, 3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.time_group.setItem(7, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.time_group.setItem(7, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.time_group.setItem(7, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.time_group.setItem(7, 3, item)
        self.time_group.horizontalHeader().setVisible(True)
        self.time_group.horizontalHeader().setDefaultSectionSize(75)
        self.time_group.verticalHeader().setVisible(False)
        self.add_time = QtWidgets.QPushButton(self.subTime_group)
        self.add_time.setGeometry(QtCore.QRect(350, 70, 75, 23))
        self.add_time.setObjectName("add_time")
        self.del_time = QtWidgets.QPushButton(self.subTime_group)
        self.del_time.setGeometry(QtCore.QRect(350, 100, 75, 23))
        self.del_time.setObjectName("del_time")
        self.init_time = QtWidgets.QPushButton(self.subTime_group)
        self.init_time.setGeometry(QtCore.QRect(350, 160, 75, 23))
        self.init_time.setObjectName("init_time")
        self.time_all = QtWidgets.QPushButton(self.subTime_group)
        self.time_all.setGeometry(QtCore.QRect(350, 130, 75, 23))
        self.time_all.setObjectName("time_all")
        self.label = QtWidgets.QLabel(self.subTime_group)
        self.label.setGeometry(QtCore.QRect(40, 30, 281, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label.setWordWrap(False)
        self.label.setObjectName("label")
        self.gift_month = QtWidgets.QLineEdit(self.subTime_group)
        self.gift_month.setGeometry(QtCore.QRect(280, 32, 31, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.gift_month.setFont(font)
        self.gift_month.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.gift_month.setObjectName("gift_month")
        self.label_4 = QtWidgets.QLabel(self.subTime_group)
        self.label_4.setGeometry(QtCore.QRect(320, 30, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_4.setWordWrap(False)
        self.label_4.setObjectName("label_4")
        self.check_gift = QtWidgets.QCheckBox(self.subTime_group)
        self.check_gift.setGeometry(QtCore.QRect(20, 35, 21, 16))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.check_gift.setFont(font)
        self.check_gift.setText("")
        self.check_gift.setChecked(False)
        self.check_gift.setObjectName("check_gift")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.sub_list, self.checkBox_1)
        Form.setTabOrder(self.checkBox_1, self.checkBox_2)
        Form.setTabOrder(self.checkBox_2, self.checkBox_3)
        Form.setTabOrder(self.checkBox_3, self.lineEdit_1)
        Form.setTabOrder(self.lineEdit_1, self.lineEdit_2)
        Form.setTabOrder(self.lineEdit_2, self.lineEdit_3)
        Form.setTabOrder(self.lineEdit_3, self.tier_all)
        Form.setTabOrder(self.tier_all, self.tier_reset)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.tier_group.setTitle(_translate("Form", "訂閱階級"))
        self.label_1.setText(_translate("Form", "Tier 1"))
        self.label_2.setText(_translate("Form", "Tier 2"))
        self.label_3.setText(_translate("Form", "Tier 3"))
        self.lineEdit_1.setText(_translate("Form", "1.0"))
        self.lineEdit_2.setText(_translate("Form", "1.0"))
        self.lineEdit_3.setText(_translate("Form", "1.0"))
        self.tier_all.setText(_translate("Form", "全選"))
        self.tier_reset.setText(_translate("Form", "歸零"))
        self.label_award.setText(_translate("Form", "獎品清單"))
        self.label_sub.setText(_translate("Form", "訂閱名單"))
        self.label_awarder.setText(_translate("Form", "分子在這裡"))
        self.add_award.setText(_translate("Form", "新增"))
        self.load_sub.setText(_translate("Form", "匯入名單"))
        self.awarder_out.setText(_translate("Form", "分子滾出來"))
        self.load_award.setText(_translate("Form", "匯入獎品"))
        self.save_awarder.setText(_translate("Form", "儲存名單"))
        self.tenure.setText(_translate("Form", "總訂閱時間"))
        self.streak.setText(_translate("Form", "連續訂閱時間"))
        self.clear_awarder.setText(_translate("Form", "清除名單"))
        self.awarder_out_all.setText(_translate("Form", "分子全滾出來"))
        item = self.awarder_list.horizontalHeaderItem(0)
        item.setText(_translate("Form", "獎項"))
        item = self.awarder_list.horizontalHeaderItem(1)
        item.setText(_translate("Form", "中獎者"))
        item = self.awarder_list.horizontalHeaderItem(2)
        item.setText(_translate("Form", "層級"))
        item = self.awarder_list.horizontalHeaderItem(3)
        item.setText(_translate("Form", "訂閱時間"))
        self.subTime_group.setTitle(_translate("Form", "訂閱時間"))
        item = self.time_group.verticalHeaderItem(0)
        item.setText(_translate("Form", "1"))
        item = self.time_group.verticalHeaderItem(1)
        item.setText(_translate("Form", "2"))
        item = self.time_group.verticalHeaderItem(2)
        item.setText(_translate("Form", "3"))
        item = self.time_group.verticalHeaderItem(3)
        item.setText(_translate("Form", "4"))
        item = self.time_group.verticalHeaderItem(4)
        item.setText(_translate("Form", "5"))
        item = self.time_group.verticalHeaderItem(5)
        item.setText(_translate("Form", "6"))
        item = self.time_group.verticalHeaderItem(6)
        item.setText(_translate("Form", "7"))
        item = self.time_group.verticalHeaderItem(7)
        item.setText(_translate("Form", "8"))
        item = self.time_group.horizontalHeaderItem(1)
        item.setText(_translate("Form", "開始月份"))
        item = self.time_group.horizontalHeaderItem(2)
        item.setText(_translate("Form", "結束月份"))
        item = self.time_group.horizontalHeaderItem(3)
        item.setText(_translate("Form", "倍率"))
        __sortingEnabled = self.time_group.isSortingEnabled()
        self.time_group.setSortingEnabled(False)
        item = self.time_group.item(0, 1)
        item.setText(_translate("Form", "1"))
        item = self.time_group.item(0, 2)
        item.setText(_translate("Form", "3"))
        item = self.time_group.item(0, 3)
        item.setText(_translate("Form", "1.0"))
        item = self.time_group.item(1, 1)
        item.setText(_translate("Form", "4"))
        item = self.time_group.item(1, 2)
        item.setText(_translate("Form", "6"))
        item = self.time_group.item(1, 3)
        item.setText(_translate("Form", "1.0"))
        item = self.time_group.item(2, 1)
        item.setText(_translate("Form", "7"))
        item = self.time_group.item(2, 2)
        item.setText(_translate("Form", "9"))
        item = self.time_group.item(2, 3)
        item.setText(_translate("Form", "1.0"))
        item = self.time_group.item(3, 1)
        item.setText(_translate("Form", "10"))
        item = self.time_group.item(3, 2)
        item.setText(_translate("Form", "12"))
        item = self.time_group.item(3, 3)
        item.setText(_translate("Form", "1.0"))
        item = self.time_group.item(4, 1)
        item.setText(_translate("Form", "13"))
        item = self.time_group.item(4, 2)
        item.setText(_translate("Form", "24"))
        item = self.time_group.item(4, 3)
        item.setText(_translate("Form", "1.0"))
        item = self.time_group.item(5, 1)
        item.setText(_translate("Form", "25"))
        item = self.time_group.item(5, 2)
        item.setText(_translate("Form", "36"))
        item = self.time_group.item(5, 3)
        item.setText(_translate("Form", "1.0"))
        item = self.time_group.item(6, 1)
        item.setText(_translate("Form", "37"))
        item = self.time_group.item(6, 2)
        item.setText(_translate("Form", "48"))
        item = self.time_group.item(6, 3)
        item.setText(_translate("Form", "1.0"))
        item = self.time_group.item(7, 1)
        item.setText(_translate("Form", "49"))
        item = self.time_group.item(7, 2)
        item.setText(_translate("Form", "200"))
        item = self.time_group.item(7, 3)
        item.setText(_translate("Form", "1.0"))
        self.time_group.setSortingEnabled(__sortingEnabled)
        self.add_time.setText(_translate("Form", "新增"))
        self.del_time.setText(_translate("Form", "刪除"))
        self.init_time.setText(_translate("Form", "預設"))
        self.time_all.setText(_translate("Form", "全選"))
        self.label.setText(_translate("Form", "排除被送訂閱且訂閱未滿(不包含)"))
        self.gift_month.setText(_translate("Form", "99"))
        self.label_4.setText(_translate("Form", "月"))

